### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by jaewonchu** [Cmeo97/Alpha-TCVAE#1]
Hello, 
thanks for the great research.
I read your paper alpha-TCVAE but there is no code on git. 
When will the source code be uploaded?

**Comment by Cmeo97** [comment]
Unfortunately, it has been a very busy period for me, I had submissions to ICML, NeurIPs and related Workshops. I will try to release it this summer, or after the next ICLR submission deadline. Depending on when I find time. Sorry for the inconvenience.
